import RQProvider from "@/components/RQProvider";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import ToastProvider from "@/components/RQtoastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ToastProvider>
          <RQProvider>{children}</RQProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
